---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/site
  label: Pages
  create: all
  match: "**/*"
  exclude: _media
  templates:
  - modular-page
- type: heading
  label: Media Library
- type: directory
  path: src/site/_media/images
  label: Images
  create: all
  match: "**/*"
  new_doc_ext: json
  templates:
  - entity-image
  - media-remote-image
upload_dir: src/site/_uploads
public_path: "~/_uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm ci
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
